#!/usr/bin/env python3

"""
Construct a teleop node
"""
import rospy
from team1_teleop.teleop_node_logic import TeleopNode


if __name__ == '__main__':
    name = "teleop_node"
    # rospy.init_node(name, anonymous=True)
    node = TeleopNode()
    node.main(name, name)
    rospy.on_shutdown(node.shutdown_hook)
    rospy.spin()
