#!/usr/bin/env python3

"""
Construct a teleop node
"""
import rospy
from team1_teleop.teleop_node_logic import TeleopNode


if __name__ == '__main__':
    rospy.init_node('teleop_node', anonymous=True)
    node = TeleopNode()
    rospy.on_shutdown(node.shutdown_hook)
    rospy.spin()
